language: node_js

node_js:
  - "6.9"

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c "CREATE ROLE arig LOGIN ENCRYPTED PASSWORD 'md5ebbc2a4c2462fcf3614c4c4d85afa9f3' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;" -U postgres
  - psql -c "CREATE DATABASE robots WITH OWNER = arig;" -U postgres

script:
  - npm run migratedb
  - node index.js robots
