language: node_js
sudo: required

env:
  - INFLUXDB_DOCKER_IMAGE="influxdb:1.3-alpine"

node_js:
  - "6.9"

addons:
  postgresql: "9.6"

services:
  - postgresql
  - docker

before_script:
  # Copie les scripts SQL de tests
  - cp -vf flyway-*/sql-tests/* flyway-*/sql/

  # Configuration de la BDD PostgreSQL
  - psql -c "CREATE ROLE arig LOGIN ENCRYPTED PASSWORD 'md5ebbc2a4c2462fcf3614c4c4d85afa9f3' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;" -U postgres
  - psql -c "CREATE DATABASE robots WITH OWNER = arig;" -U postgres

  # Création et configuration d'un instance InfluxDB
  - docker pull ${INFLUXDB_DOCKER_IMAGE}
  - docker run -d -p 8086:8086 ${INFLUXDB_DOCKER_IMAGE}
  - docker run --network="host" --rm ${INFLUXDB_DOCKER_IMAGE} influx -execute 'CREATE DATABASE robots'
  - docker run --network="host" --rm ${INFLUXDB_DOCKER_IMAGE} influx -execute "CREATE USER arig WITH PASSWORD 'arig'"
  - docker run --network="host" --rm ${INFLUXDB_DOCKER_IMAGE} influx -execute 'GRANT ALL ON robots TO arig'


script:
  - npm run migratedb
  - node index.js robots
  - node index.js execs 0
  - node index.js save 0 12345
